name: Build Android Kernel

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            dwarves \
            flex \
            gawk \
            git \
            libelf-dev \
            libssl-dev \
            lz4 \
            rsync \
            unzip \
            xz-utils \
            zip \
            zstd

      - name: Cache toolchain
        id: toolchain-cache
        uses: actions/cache@v5
        with:
          path: $HOME/toolchain
          key: toolchain-cache

      - name: Get toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          RELEASE: clang-r584948
        run: |
          mkdir -p "$HOME/toolchain"
          cd "$HOME/toolchain"
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/$RELEASE.tar.gz
          tar xvf $RELEASE.tar.gz
          rm $RELEASE.tar.gz

      - name: Build kernel
        run: |
          set -euo pipefail
          chmod +x ./build.sh
          ./build.sh

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          if-no-files-found: warn
          path: |
            AnyKernel/*.zip
